// src/views/Login.vue
<template>
  <div class="auth-page">
    <div class="auth-container">
      <div class="auth-card card">
        <div class="auth-header">
          <h1>Welcome Back</h1>
          <p>Sign in to your Heritage Handicrafts account</p>
        </div>

        <form @submit.prevent="handleLogin" class="auth-form">
          <div class="form-group">
            <label>Email Address</label>
            <input 
              v-model="form.email" 
              type="email" 
              placeholder="you@example.com"
              required
            >
          </div>

          <div class="form-group">
            <label>Password</label>
            <input 
              v-model="form.password" 
              type="password" 
              placeholder="••••••••"
              required
            >
          </div>

          <div class="form-check">
            <input 
              v-model="form.rememberMe" 
              type="checkbox" 
              id="remember"
            >
            <label for="remember">Remember me</label>
          </div>

          <button type="submit" class="btn btn-lg btn-block login-btn">
            Sign In
          </button>
        </form>

        <div class="divider">
          <span>OR</span>
        </div>

        <div class="social-login">
          <button class="social-btn google">
            <span>🔍</span> Google
          </button>
          <button class="social-btn facebook">
            <span>👤</span> Facebook
          </button>
        </div>

        <p class="auth-footer">
          Don't have an account? 
          <router-link to="/register" class="auth-link">Sign up here</router-link>
        </p>

        <p class="forgot-password">
          <router-link to="/forgot-password" class="auth-link">Forgot your password?</router-link>
        </p>
      </div>

      <div class="auth-benefits">
        <h3>Why Create an Account?</h3>
        <ul>
          <li>✓ Track your orders</li>
          <li>✓ Save favorite products</li>
          <li>✓ Faster checkout</li>
          <li>✓ Exclusive offers</li>
          <li>✓ Support artisans directly</li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const router = useRouter()
const authStore = useAuthStore()

const form = ref({
  email: '',
  password: '',
  rememberMe: false
})

const handleLogin = () => {
  if (!form.value.email || !form.value.password) {
    alert('Please fill in all fields')
    return
  }

  // Simulate login
  const userData = {
    id: Date.now(),
    email: form.value.email,
    name: form.value.email.split('@')[0],
    avatar: '👤'
  }

  authStore.login(userData)
  alert(`Welcome back, ${userData.name}!`)
  router.push('/')
}
</script>

<style scoped>
.auth-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #f8f6f3 0%, #f0ebe5 100%);
  padding: 2rem;
}

.auth-container {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 3rem;
  max-width: 900px;
  width: 100%;
}

.auth-card {
  padding: 2.5rem !important;
}

.auth-header {
  text-align: center;
  margin-bottom: 2rem;
}

.auth-header h1 {
  font-size: 1.8rem;
  margin-bottom: 0.5rem;
}

.auth-header p {
  color: var(--text-light);
}

.auth-form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.form-group {
  display: flex;
  flex-direction: column;
}

.form-group label {
  font-weight: 600;
  margin-bottom: 0.5rem;
  font-size: 0.95rem;
}

.form-group input {
  padding: 0.75rem;
  border: 1px solid var(--border-color);
  border-radius: 6px;
  font-size: 1rem;
  transition: all 0.3s;
}

.form-group input:focus {
  outline: none;
  border-color: var(--primary-color);
  box-shadow: 0 0 0 3px rgba(212, 165, 116, 0.1);
}

.form-check {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.form-check input {
  width: auto;
  accent-color: var(--primary-color);
}

.form-check label {
  cursor: pointer;
  font-size: 0.95rem;
  margin: 0;
}

.login-btn {
  background: var(--primary-color);
  color: white;
  font-weight: 600;
  margin-top: 0.5rem;
}

.login-btn:hover {
  background: #c9952f;
}

.divider {
  display: flex;
  align-items: center;
  gap: 1rem;
  margin: 1.5rem 0;
  color: var(--text-light);
}

.divider::before,
.divider::after {
  content: '';
  flex: 1;
  height: 1px;
  background: var(--border-color);
}

.social-login {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.social-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.75rem;
  border: 1px solid var(--border-color);
  background: white;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 500;
  transition: all 0.3s;
}

.social-btn:hover {
  border-color: var(--primary-color);
  background: var(--light-bg);
}

.auth-footer {
  text-align: center;
  font-size: 0.95rem;
  margin-bottom: 1rem;
}

.auth-link {
  color: var(--primary-color);
  text-decoration: none;
  font-weight: 600;
}

.auth-link:hover {
  text-decoration: underline;
}

.forgot-password {
  text-align: center;
  font-size: 0.9rem;
}

.auth-benefits {
  background: white;
  padding: 2rem;
  border-radius: 12px;
  border: 2px solid var(--border-color);
}

.auth-benefits h3 {
  margin-bottom: 1.5rem;
  font-size: 1.2rem;
}

.auth-benefits ul {
  list-style: none;
  padding: 0;
}

.auth-benefits li {
  padding: 0.75rem 0;
  color: var(--text-dark);
  font-size: 0.95rem;
  border-bottom: 1px solid var(--border-color);
}

.auth-benefits li:last-child {
  border-bottom: none;
}

@media (max-width: 1024px) {
  .auth-container {
    grid-template-columns: 1fr;
    gap: 2rem;
  }

  .auth-benefits {
    display: none;
  }
}

@media (max-width: 480px) {
  .auth-page {
    padding: 1rem;
  }

  .auth-card {
    padding: 1.5rem !important;
  }

  .auth-header h1 {
    font-size: 1.5rem;
  }

  .social-login {
    grid-template-columns: 1fr;
  }
}
</style>

// LibraryPro/frontend/src/pages/Login.tsx
import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { useAuthStore } from '../store/authStore'
import { apiClient } from '../services/api'
import { BookOpen } from 'lucide-react'

export default function Login() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const navigate = useNavigate()
  const { login } = useAuthStore()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setIsLoading(true)

    try {
      const response = await apiClient.login(email, password)
      const { token, user } = response.data

      login(user, token)
      navigate('/')
    } catch (err: any) {
      setError(err.response?.data?.message || 'Login failed. Please try again.')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-600 to-blue-800 flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-md p-8">
        {/* Header */}
        <div className="flex justify-center mb-8">
          <div className="flex items-center gap-2">
            <BookOpen className="text-blue-600" size={32} />
            <h1 className="text-3xl font-bold text-gray-900">LibraryPro</h1>
          </div>
        </div>

        <h2 className="text-2xl font-bold text-gray-900 mb-2">Welcome Back</h2>
        <p className="text-gray-600 mb-6">Sign in to your account to continue</p>

        {/* Error Message */}
        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg mb-6">
            {error}
          </div>
        )}

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Email Address
            </label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              placeholder="you@example.com"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Password
            </label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              placeholder="••••••••"
              required
            />
          </div>

          <button
            type="submit"
            disabled={isLoading}
            className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 text-white font-medium py-2 rounded-lg transition"
          >
            {isLoading ? 'Signing in...' : 'Sign In'}
          </button>
        </form>

        {/* Footer */}
        <div className="mt-6 text-center">
          <p className="text-gray-600">
            Don't have an account?{' '}
            <Link to="/register" className="text-blue-600 hover:text-blue-700 font-medium">
              Register here
            </Link>
          </p>
        </div>

        {/* Demo Credentials */}
        <div className="mt-6 pt-6 border-t border-gray-200">
          <p className="text-xs text-gray-500 mb-2">Demo Credentials:</p>
          <div className="bg-gray-50 p-3 rounded text-xs space-y-1">
            <p className="text-gray-700">
              <strong>Member:</strong> member@library.com / password123
            </p>
            <p className="text-gray-700">
              <strong>Librarian:</strong> librarian@library.com / password123
            </p>
            <p className="text-gray-700">
              <strong>Admin:</strong> admin@library.com / password123
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
